Watching for file changes with StatReloader
"GET /account/profile/ HTTP/1.1" 200 18122
"GET /account/profile/ HTTP/1.1" 200 18122
"GET /account/profile/ HTTP/1.1" 200 18122
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\admin.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\admin.py changed, reloading.
Watching for file changes with StatReloader
"GET /account/profile/ HTTP/1.1" 200 18122
"GET /admin/ HTTP/1.1" 200 24870
"GET /admin/account/profile/ HTTP/1.1" 200 22003
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/add/ HTTP/1.1" 200 25220
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /admin/auth/user/add/ HTTP/1.1" 200 25414
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /admin/auth/user/add/ HTTP/1.1" 200 25414
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/auth/user/8/change/ HTTP/1.1" 200 37145
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15492
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /admin/account/profile/ HTTP/1.1" 200 22003
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\apps.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/auth/user/add/ HTTP/1.1" 200 25221
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"POST /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/auth/user/9/change/ HTTP/1.1" 200 37145
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/account/profile/ HTTP/1.1" 200 23658
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/account/profile/1/change/ HTTP/1.1" 200 24580
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/calendar-icons.svg HTTP/1.1" 200 1094
"POST /admin/account/profile/1/change/ HTTP/1.1" 302 0
"GET /admin/account/profile/ HTTP/1.1" 200 23886
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/account/profile/1/change/ HTTP/1.1" 200 24599
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /account/profile/ HTTP/1.1" 200 18122
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\forms.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /account/profile/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\views.py", line 27, in dashboard
    return render(request,
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'edit-profile' not found. 'edit-profile' is not a valid view function or pattern name.
"GET /account/profile/ HTTP/1.1" 500 182877
"GET /account/profile/ HTTP/1.1" 200 18196
Internal Server Error: /account/profile/edit/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\views.py", line 85, in edit_profile
    profile_form = ProfileEditForm(instance=request.user.profile)
                                            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
"GET /account/profile/edit/ HTTP/1.1" 500 93818
"GET /account/profile/ HTTP/1.1" 200 18196
"POST /account/logout/ HTTP/1.1" 302 0
"GET /blog/ HTTP/1.1" 200 27634
"GET /account/profile/ HTTP/1.1" 302 0
"GET /account/login/?next=/account/profile/ HTTP/1.1" 200 18342
"POST /account/login/?next=/account/profile/ HTTP/1.1" 302 0
"GET /account/profile/ HTTP/1.1" 200 18187
"GET /account/profile/edit/ HTTP/1.1" 200 19028
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /account/profile/ HTTP/1.1" 200 18187
"GET /account/profile/edit/ HTTP/1.1" 200 19028
Internal Server Error: /account/profile/edit/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\views.py", line 93, in edit_profile
    return redirect(request, 'account:dashboard')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '<WSGIRequest: POST '/account/profile/edit/'>' not found. '<WSGIRequest: POST '/account/profile/edit/'>' is not a valid view function or pattern name.
"POST /account/profile/edit/ HTTP/1.1" 500 106704
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /account/profile/edit/ HTTP/1.1" 302 0
"GET /account/profile/ HTTP/1.1" 200 18387
"GET /account/profile/ HTTP/1.1" 200 18207
"GET /account/profile/ HTTP/1.1" 200 18334
Not Found: /account/profile/users/2024/09/12/Python-logo-notext.svg_OAnWLY0.png
"GET /account/profile/users/2024/09/12/Python-logo-notext.svg_OAnWLY0.png HTTP/1.1" 404 16817
"GET /account/profile/ HTTP/1.1" 200 18341
"GET /media/users/2024/09/12/Python-logo-notext.svg_OAnWLY0.png HTTP/1.1" 200 96986
"GET /account/profile/edit/ HTTP/1.1" 200 19331
"POST /account/profile/edit/ HTTP/1.1" 302 0
"GET /account/profile/ HTTP/1.1" 200 18423
"GET /media/users/2024/09/12/c-plus-plus-93c7ddd5cc.png HTTP/1.1" 200 12986
"GET /account/profile/edit/ HTTP/1.1" 200 19315
"GET /account/profile/ HTTP/1.1" 200 18333
"GET /account/profile/edit/ HTTP/1.1" 200 19315
"POST /account/profile/edit/ HTTP/1.1" 200 19505
"GET /account/profile/ HTTP/1.1" 200 18333
"GET /media/users/2024/09/12/c-plus-plus-93c7ddd5cc.png HTTP/1.1" 304 0
"GET /blog/post/create/ HTTP/1.1" 200 19708
"GET /account/profile/ HTTP/1.1" 200 18333
"GET /admin/auth/user/add/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/auth/user/add/ HTTP/1.1" 200 16888
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 88, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 107, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\signals.py", line 16, in save_profile
    instance.profile.save()
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
"POST /admin/login/?next=/admin/auth/user/add/ HTTP/1.1" 500 197281
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 17326
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 88, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 107, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\signals.py", line 16, in save_profile
    instance.profile.save()
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
"POST /admin/login/?next=/admin/ HTTP/1.1" 500 196708
Forbidden (CSRF token from POST incorrect.): /account/logout/
"POST /account/logout/ HTTP/1.1" 403 15643
Forbidden (CSRF token from POST incorrect.): /account/logout/
"POST /account/logout/ HTTP/1.1" 403 15643
Forbidden (CSRF token from POST incorrect.): /admin/login/
"POST /admin/login/?next=/admin/ HTTP/1.1" 403 15648
"GET /blog/ HTTP/1.1" 200 27634
"GET /account/profile/ HTTP/1.1" 302 0
"GET /account/login/?next=/account/profile/ HTTP/1.1" 200 18341
"GET /blog/ HTTP/1.1" 200 27634
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 17326
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 88, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 107, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\signals.py", line 16, in save_profile
    instance.profile.save()
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
"POST /admin/login/?next=/admin/ HTTP/1.1" 500 196708
Forbidden (CSRF token from POST incorrect.): /account/login/
"POST /account/login/?next=/account/profile/ HTTP/1.1" 403 15664
Forbidden (CSRF token from POST incorrect.): /account/login/
"POST /account/login/?next=/account/profile/ HTTP/1.1" 403 15664
Watching for file changes with StatReloader
Forbidden (CSRF token from POST incorrect.): /account/login/
"POST /account/login/?next=/account/profile/ HTTP/1.1" 403 15665
"GET /blog/ HTTP/1.1" 200 27634
"GET /account/profile/ HTTP/1.1" 302 0
"GET /account/login/?next=/account/profile/ HTTP/1.1" 200 18342
Internal Server Error: /account/login/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 88, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 107, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\signals.py", line 16, in save_profile
    instance.profile.save()
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
"POST /account/login/?next=/account/profile/ HTTP/1.1" 500 178165
"GET /account/login/?next=/account/profile/ HTTP/1.1" 200 18341
"GET /account/login/?next=/account/profile/ HTTP/1.1" 200 18342
"GET /account/login/?next=/account/profile/ HTTP/1.1" 200 18341
"GET /account/login/?next=/account/profile/ HTTP/1.1" 200 18341
"GET /account/login/?next=/account/profile/ HTTP/1.1" 200 18341
Internal Server Error: /account/login/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 88, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 107, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\signals.py", line 16, in save_profile
    instance.profile.save()
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
"POST /account/login/?next=/account/profile/ HTTP/1.1" 500 178165
"GET /account/login/?next=/account/profile/ HTTP/1.1" 200 18342
"POST /account/login/?next=/account/profile/ HTTP/1.1" 302 0
"GET /account/profile/ HTTP/1.1" 200 18333
"GET /media/users/2024/09/12/c-plus-plus-93c7ddd5cc.png HTTP/1.1" 200 12986
"GET /blog/ HTTP/1.1" 200 27634
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 16846
"POST /account/logout/ HTTP/1.1" 302 0
"GET /blog/ HTTP/1.1" 200 27634
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 17327
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 88, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\views.py", line 107, in form_valid
    auth_login(self.request, form.get_user())
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 152, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\base_user.py", line 78, in save
    super().save(*args, **kwargs)
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\signals.py", line 16, in save_profile
    instance.profile.save()
    ^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 525, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.profile.RelatedObjectDoesNotExist: User has no profile.
"POST /admin/login/?next=/admin/ HTTP/1.1" 500 196708
Forbidden (CSRF token from POST incorrect.): /admin/login/
"POST /admin/login/?next=/admin/ HTTP/1.1" 403 15648
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 17326
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 17326
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 21227
"GET /admin/auth/user/ HTTP/1.1" 200 28940
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/1/change/ HTTP/1.1" 200 36993
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/account/profile/ HTTP/1.1" 200 24135
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/account/profile/2/change/ HTTP/1.1" 200 24584
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/account/profile/ HTTP/1.1" 200 24135
Internal Server Error: /account/profile/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'ImageFieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\views.py", line 27, in dashboard
    return render(request,
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\files.py", line 66, in url
    self._require_file()
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\files.py", line 41, in _require_file
    raise ValueError(
ValueError: The 'photo' attribute has no file associated with it.
"GET /account/profile/ HTTP/1.1" 500 182563
Internal Server Error: /account/profile/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'ImageFieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\views.py", line 27, in dashboard
    return render(request,
           ^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\test\utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\files.py", line 66, in url
    self._require_file()
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\db\models\fields\files.py", line 41, in _require_file
    raise ValueError(
ValueError: The 'photo' attribute has no file associated with it.
"GET /account/profile/ HTTP/1.1" 500 182700
"GET /account/profile/ HTTP/1.1" 200 18187
"GET /account/profile/edit/ HTTP/1.1" 200 19036
"POST /account/profile/edit/ HTTP/1.1" 302 0
"GET /account/profile/ HTTP/1.1" 200 18422
"GET /media/users/2024/09/12/C_Sharp_Logo_2023.svg.png HTTP/1.1" 200 2920
"POST /account/logout/ HTTP/1.1" 302 0
"GET /blog/ HTTP/1.1" 200 27634
"GET /account/profile/ HTTP/1.1" 302 0
"GET /account/login/?next=/account/profile/ HTTP/1.1" 200 18341
"POST /account/login/?next=/account/profile/ HTTP/1.1" 302 0
"GET /account/profile/ HTTP/1.1" 200 18335
"GET /media/users/2024/09/12/c-plus-plus-93c7ddd5cc.png HTTP/1.1" 304 0
"GET /account/profile/edit/ HTTP/1.1" 200 19315
"POST /account/profile/edit/ HTTP/1.1" 302 0
"GET /account/profile/ HTTP/1.1" 200 18427
"GET /account/profile/edit/ HTTP/1.1" 200 19317
"POST /account/profile/edit/ HTTP/1.1" 302 0
"GET /account/profile/ HTTP/1.1" 200 18427
"GET /media/users/2024/09/12/c-plus-plus-93c7ddd5cc.png HTTP/1.1" 304 0
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\account\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /account/profile/ HTTP/1.1" 200 18338
"GET /media/users/2024/09/12/c-plus-plus-93c7ddd5cc.png HTTP/1.1" 304 0
"GET /account/profile/ HTTP/1.1" 200 18337
"GET /account/profile/ HTTP/1.1" 200 18337
"GET /account/profile/edit/ HTTP/1.1" 200 19317
"POST /account/profile/edit/ HTTP/1.1" 200 19485
"POST /account/profile/edit/ HTTP/1.1" 302 0
"GET /account/profile/ HTTP/1.1" 200 18427
Watching for file changes with StatReloader
"GET /blog/ HTTP/1.1" 200 27635
"GET /static/css/card.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/images/logo.png HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"GET /static/images/sky.jpg HTTP/1.1" 304 0
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 15798
"GET /account/profile/ HTTP/1.1" 200 18337
"GET /media/users/2024/09/12/c-plus-plus-93c7ddd5cc.png HTTP/1.1" 304 0
"GET /account/profile/edit/ HTTP/1.1" 200 19317
"GET /account/profile/edit/ HTTP/1.1" 200 19317
Watching for file changes with StatReloader
"GET /blog/post/1/ HTTP/1.1" 200 18718
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 14601
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 16675
"GET /media/post/images/C_Sharp_Logo_2023.svg.png HTTP/1.1" 200 2920
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4742
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 15798
"GET /blog/post/create/ HTTP/1.1" 200 19708
"POST /blog/post/create/ HTTP/1.1" 302 0
"GET /blog/post/32/ HTTP/1.1" 200 18208
"GET /media/default.png HTTP/1.1" 200 136879
"GET /blog/post/create/ HTTP/1.1" 200 19708
"GET /blog/cards/ HTTP/1.1" 200 49803
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /blog/ HTTP/1.1" 200 27635
"GET /blog/search/?q=python HTTP/1.1" 200 19606
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /blog/search/?q=python HTTP/1.1" 200 19608
"GET /blog/search/?q=python HTTP/1.1" 200 19608
"GET /blog/ HTTP/1.1" 200 27634
"GET /blog/search/?q=python HTTP/1.1" 200 19608
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /blog/search/?q=python HTTP/1.1" 200 19608
"GET /blog/redirect HTTP/1.1" 301 0
Internal Server Error: /blog/redirect/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 257, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 244, in get_redirect_url
    if self.url:
       ^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-list-cards' not found. 'post-list-cards' is not a valid view function or pattern name.
"GET /blog/redirect/ HTTP/1.1" 500 108668
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /blog/redirect/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 257, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 244, in get_redirect_url
    if self.url:
       ^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-list' not found. 'post-list' is not a valid view function or pattern name.
"GET /blog/redirect/ HTTP/1.1" 500 108709
Internal Server Error: /blog/redirect/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 257, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 244, in get_redirect_url
    if self.url:
       ^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-list' not found. 'post-list' is not a valid view function or pattern name.
"GET /blog/redirect/ HTTP/1.1" 500 108709
Internal Server Error: /blog/redirect/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 257, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 244, in get_redirect_url
    if self.url:
       ^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-list' not found. 'post-list' is not a valid view function or pattern name.
"GET /blog/redirect/ HTTP/1.1" 500 108709
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /blog/redirect/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 257, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 244, in get_redirect_url
    if self.url:
       ^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'posts-list' not found. 'posts-list' is not a valid view function or pattern name.
"GET /blog/redirect/ HTTP/1.1" 500 108725
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /blog/redirect/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 257, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 244, in get_redirect_url
    if self.url:
       ^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'posts-list' not found. 'posts-list' is not a valid view function or pattern name.
"GET /blog/redirect/ HTTP/1.1" 500 108725
Internal Server Error: /blog/redirect/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 257, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 244, in get_redirect_url
    if self.url:
       ^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'posts-list' not found. 'posts-list' is not a valid view function or pattern name.
"GET /blog/redirect/ HTTP/1.1" 500 108725
Internal Server Error: /blog/redirect/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 257, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 244, in get_redirect_url
    if self.url:
       ^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'posts-list' not found. 'posts-list' is not a valid view function or pattern name.
"GET /blog/redirect/ HTTP/1.1" 500 108725
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /blog/redirect/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 257, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 244, in get_redirect_url
    if self.url:
       ^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-list' not found. 'post-list' is not a valid view function or pattern name.
"GET /blog/redirect/ HTTP/1.1" 500 108709
Not Found: /blog/redire
"GET /blog/redire HTTP/1.1" 404 19301
Internal Server Error: /blog/redirect/
Traceback (most recent call last):
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 257, in get
    url = self.get_redirect_url(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\views\generic\base.py", line 244, in get_redirect_url
    if self.url:
       ^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\utils\functional.py", line 187, in __wrapper__
    result = func(*self._args, **self._kw)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vlad\PycharmProjects\pythonProjectDjango\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-list' not found. 'post-list' is not a valid view function or pattern name.
"GET /blog/redirect/ HTTP/1.1" 500 108572
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /blog/redirect/ HTTP/1.1" 302 0
"GET /blog/ HTTP/1.1" 200 27634
"GET /blog/redirect/ HTTP/1.1" 302 0
"GET /blog/ HTTP/1.1" 200 27634
C:\Users\Vlad\PycharmProjects\pythonProjectDjango\itstep\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /blog/ HTTP/1.1" 200 27634
"GET /blog/redirect/ HTTP/1.1" 302 0
"GET /blog/ HTTP/1.1" 200 27634
"GET /blog/search/?q=pyth HTTP/1.1" 200 19604
"GET /blog/ HTTP/1.1" 200 27634
"GET /blog/redirect/ HTTP/1.1" 302 0
"GET /blog/ HTTP/1.1" 200 27634
"GET /blog/redirect/ HTTP/1.1" 302 0
"GET /blog/ HTTP/1.1" 200 27634
